<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Auth.Client</RootNamespace>
        <AssemblyName>Auth.Client</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\core\SetNet\SetNet.csproj" />
        <ProjectReference Include="..\..\..\src\serializers\SetNet.MessagePack\SetNet.MessagePack.csproj" />
        <ProjectReference Include="..\..\..\src\security\SetNet.Auth\SetNet.Auth.csproj" />
        <ProjectReference Include="..\Auth.Shared\Auth.Shared.csproj" />
    </ItemGroup>

</Project>
