<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Voice.Client</RootNamespace>
        <AssemblyName>Voice.Client</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\core\SetNet\SetNet.csproj" />
        <ProjectReference Include="..\..\..\src\serializers\SetNet.MessagePack\SetNet.MessagePack.csproj" />
        <ProjectReference Include="..\..\..\src\realtime\SetNet.Voice\SetNet.Voice.csproj" />
        <ProjectReference Include="..\Voice.Shared\Voice.Shared.csproj" />
    </ItemGroup>

</Project>
