<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>StateSync.Shared</RootNamespace>
        <AssemblyName>StateSync.Shared</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\realtime\SetNet.StateSync\SetNet.StateSync.csproj" />
    </ItemGroup>

</Project>
