using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace SetNet.Docs
{
    /// <summary>A discovered <c>[MessageHandler]</c>: its wire type id, direction, payload type and handler class.</summary>
    public sealed class HandlerDoc
    {
        /// <summary>The message wire type id.</summary>
        public ushort MessageType { get; set; }
        /// <summary>"server" or "client" (which side handles it), or "?" if undetermined.</summary>
        public string Direction { get; set; } = "?";
        /// <summary>The payload type name.</summary>
        public string Payload { get; set; } = "";
        /// <summary>The handler class name.</summary>
        public string Handler { get; set; } = "";
    }

    /// <summary>A discovered unified-protocol channel: its id, name and the ops/events/service classes on it.</summary>
    public sealed class ChannelDoc
    {
        /// <summary>The channel id.</summary>
        public ushort Channel { get; set; }
        /// <summary>The friendly channel name from <c>SetNet.Protocol.Channels</c>, if known.</summary>
        public string Name { get; set; } = "";
        /// <summary>Classes that handle this channel (an <c>IChannelService</c> or an <c>[Op]</c>-routed class).</summary>
        public List<string> Services { get; } = new List<string>();
        /// <summary>Discovered <c>[Op]</c> ids → method name.</summary>
        public SortedDictionary<ushort, string> Ops { get; } = new SortedDictionary<ushort, string>();
        /// <summary>Discovered <c>[Event]</c> ids → method name.</summary>
        public SortedDictionary<ushort, string> Events { get; } = new SortedDictionary<ushort, string>();
    }

    /// <summary>A discovered <c>[RpcMethod]</c>: its method id and handler.</summary>
    public sealed class RpcDoc
    {
        /// <summary>The RPC method id.</summary>
        public ushort MethodId { get; set; }
        /// <summary>The handler class.method.</summary>
        public string Handler { get; set; } = "";
    }

    /// <summary>The generated protocol report: handlers, unified-protocol channels, and RPC methods.</summary>
    public sealed class ProtocolReport
    {
        /// <summary>All <c>[MessageHandler]</c>s, ordered by type id.</summary>
        public List<HandlerDoc> Handlers { get; } = new List<HandlerDoc>();
        /// <summary>All unified-protocol channels, ordered by id.</summary>
        public List<ChannelDoc> Channels { get; } = new List<ChannelDoc>();
        /// <summary>All <c>[RpcMethod]</c>s, ordered by id.</summary>
        public List<RpcDoc> RpcMethods { get; } = new List<RpcDoc>();

        /// <summary>Renders the report as Markdown.</summary>
        public string ToMarkdown()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# SetNet protocol");
            sb.AppendLine();
            sb.AppendLine($"_Generated by SetNet.Docs — {Handlers.Count} message handler(s), {Channels.Count} channel(s), {RpcMethods.Count} RPC method(s)._");
            sb.AppendLine();

            sb.AppendLine("## Unified protocol channels");
            sb.AppendLine();
            if (Channels.Count == 0) sb.AppendLine("_None discovered._");
            else
            {
                sb.AppendLine("| Channel | Id | Ops | Events | Handled by |");
                sb.AppendLine("|---|---|---|---|---|");
                foreach (var c in Channels)
                {
                    var ops = c.Ops.Count == 0 ? "—" : string.Join(", ", c.Ops.Select(o => $"{o.Value}({o.Key})"));
                    var evs = c.Events.Count == 0 ? "—" : string.Join(", ", c.Events.Select(o => $"{o.Value}({o.Key})"));
                    var svc = c.Services.Count == 0 ? "—" : string.Join(", ", c.Services);
                    sb.AppendLine($"| {(string.IsNullOrEmpty(c.Name) ? "?" : c.Name)} | {c.Channel} | {ops} | {evs} | {svc} |");
                }
            }
            sb.AppendLine();

            sb.AppendLine("## Message handlers");
            sb.AppendLine();
            if (Handlers.Count == 0) sb.AppendLine("_None discovered._");
            else
            {
                sb.AppendLine("| Type id | Direction | Payload | Handler |");
                sb.AppendLine("|---|---|---|---|");
                foreach (var h in Handlers) sb.AppendLine($"| {h.MessageType} | {h.Direction} | {h.Payload} | {h.Handler} |");
            }
            sb.AppendLine();

            sb.AppendLine("## RPC methods");
            sb.AppendLine();
            if (RpcMethods.Count == 0) sb.AppendLine("_None discovered._");
            else
            {
                sb.AppendLine("| Method id | Handler |");
                sb.AppendLine("|---|---|");
                foreach (var r in RpcMethods) sb.AppendLine($"| {r.MethodId} | {r.Handler} |");
            }
            return sb.ToString();
        }
    }

    /// <summary>
    /// Reflects over your assemblies and documents the wire protocol: <c>[MessageHandler]</c>s, unified-protocol
    /// <c>[ProtocolChannel]</c>s (with their <c>[Op]</c>/<c>[Event]</c> ids), and <c>[RpcMethod]</c>s. Attributes are
    /// matched by name so this needs no reference to the RPC package — call it after your modules' <c>Runtime.Enable()</c>.
    /// </summary>
    public static class ProtocolDocs
    {
        /// <summary>Generates the report over the given assemblies (defaults to all loaded assemblies).</summary>
        public static ProtocolReport Generate(IEnumerable<Assembly>? assemblies = null)
        {
            var asms = (assemblies ?? AppDomain.CurrentDomain.GetAssemblies()).ToList();
            var report = new ProtocolReport();
            var channelNames = ReadChannelNames(asms);
            var channels = new Dictionary<ushort, ChannelDoc>();

            ChannelDoc Channel(ushort id)
            {
                if (!channels.TryGetValue(id, out var c))
                {
                    channels[id] = c = new ChannelDoc { Channel = id, Name = channelNames.TryGetValue(id, out var n) ? n : "" };
                }
                return c;
            }

            foreach (var asm in asms)
            foreach (var type in SafeGetTypes(asm))
            {
              try
              {
                // [MessageHandler] classes.
                var handlerAttr = SafeAttrs(type).FirstOrDefault(a => a.GetType().Name == "MessageHandlerAttribute");
                if (handlerAttr != null && TryReadUShort(handlerAttr, "MessageType", out var msgType))
                {
                    var (dir, payload) = DirectionAndPayload(type);
                    report.Handlers.Add(new HandlerDoc { MessageType = msgType, Direction = dir, Payload = payload, Handler = type.Name });
                }

                // [ProtocolChannel] classes → their channel + any [Op]/[Event] methods.
                var chanAttr = type.GetCustomAttributes().FirstOrDefault(a => a.GetType().Name == "ProtocolChannelAttribute");
                if (chanAttr != null && TryReadUShort(chanAttr, "Channel", out var chanId))
                {
                    var doc = Channel(chanId);
                    doc.Services.Add(type.Name);
                    foreach (var m in type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
                    {
                        foreach (var a in SafeAttrs(m))
                        {
                            if (a.GetType().Name == "OpAttribute" && TryReadUShort(a, "Op", out var op)) doc.Ops[op] = m.Name;
                            else if (a.GetType().Name == "EventAttribute" && TryReadUShort(a, "Op", out var ev)) doc.Events[ev] = m.Name;
                        }
                    }
                }

                // [RpcMethod] methods (matched by attribute name → no dependency on the RPC package).
                foreach (var m in type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
                {
                    var rpc = SafeAttrs(m).FirstOrDefault(a => a.GetType().Name == "RpcMethodAttribute");
                    if (rpc != null && TryReadUShort(rpc, "MethodId", out var methodId))
                        report.RpcMethods.Add(new RpcDoc { MethodId = methodId, Handler = $"{type.Name}.{m.Name}" });
                }
              }
              catch { /* skip types whose metadata/attributes can't be loaded (e.g. test-host types) */ }
            }

            report.Handlers.Sort((a, b) => a.MessageType.CompareTo(b.MessageType));
            report.RpcMethods.Sort((a, b) => a.MethodId.CompareTo(b.MethodId));
            report.Channels.AddRange(channels.Values.OrderBy(c => c.Channel));
            return report;
        }

        /// <summary>Generates the report and returns it as Markdown.</summary>
        public static string GenerateMarkdown(IEnumerable<Assembly>? assemblies = null) => Generate(assemblies).ToMarkdown();

        /// <summary>Generates the report and writes the Markdown to a file.</summary>
        public static void WriteMarkdown(string path, IEnumerable<Assembly>? assemblies = null)
        {
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(path, GenerateMarkdown(assemblies));
        }

        private static IEnumerable<Attribute> SafeAttrs(MemberInfo m)
        {
            try { return m.GetCustomAttributes(); } catch { return Array.Empty<Attribute>(); }
        }

        private static (string direction, string payload) DirectionAndPayload(Type type)
        {
            Type[] interfaces;
            try { interfaces = type.GetInterfaces(); } catch { return ("?", ""); }
            foreach (var i in interfaces)
            {
                if (!i.IsGenericType) continue;
                var name = i.GetGenericTypeDefinition().Name;
                if (name.StartsWith("IServerMessageHandler")) return ("server", i.GetGenericArguments()[0].Name);
                if (name.StartsWith("IClientMessageHandler")) return ("client", i.GetGenericArguments()[0].Name);
            }
            return ("?", "");
        }

        private static Dictionary<ushort, string> ReadChannelNames(IEnumerable<Assembly> assemblies)
        {
            var map = new Dictionary<ushort, string>();
            foreach (var asm in assemblies)
            {
                var channelsType = SafeGetTypes(asm).FirstOrDefault(t => t.FullName == "SetNet.Protocol.Channels");
                if (channelsType == null) continue;
                foreach (var f in channelsType.GetFields(BindingFlags.Public | BindingFlags.Static))
                {
                    if (!f.IsLiteral || f.FieldType != typeof(ushort)) continue;
                    var value = (ushort)f.GetRawConstantValue()!;
                    map[value] = f.Name;
                }
                break;
            }
            return map;
        }

        private static bool TryReadUShort(object attr, string prop, out ushort value)
        {
            value = 0;
            var p = attr.GetType().GetProperty(prop);
            if (p == null) return false;
            var raw = p.GetValue(attr);
            if (raw == null) return false;
            try { value = Convert.ToUInt16(raw); return true; } catch { return false; }
        }

        private static IEnumerable<Type> SafeGetTypes(Assembly asm)
        {
            try { return asm.GetTypes(); }
            catch (ReflectionTypeLoadException ex) { return ex.Types.Where(t => t != null)!; }
            catch { return Array.Empty<Type>(); }
        }
    }
}
