<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Rooms.Server</RootNamespace>
        <AssemblyName>Rooms.Server</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\core\SetNet\SetNet.csproj" />
        <ProjectReference Include="..\..\..\src\serializers\SetNet.MessagePack\SetNet.MessagePack.csproj" />
        <ProjectReference Include="..\..\..\src\realtime\SetNet.Rooms\SetNet.Rooms.csproj" />
        <ProjectReference Include="..\Rooms.Shared\Rooms.Shared.csproj" />
    </ItemGroup>

</Project>
